### ISSUE TITLE
Product Show > Product Section Checklist

### ISSUE THREAD

**Issue by chohannah** [yejinc/the-house-of-tomorrow#1]
## TO-DO LIST

- Tab + TabPanel structure
  -  [ ] organic connection by using `role`
- Common components
  -  [x] TabPanel > Header
     -  [x] Text only
     -  [x] Text + NumberBadge + IconLink
     -  [x] Text + NumberBadge + TextLink
     -  [x] Text + NumberBadge + IconButton(Dropdown) -- **mobile only**
  - [x]  TabPanel > `table`
